sudo: false
language: php
php:
  - 7.1
  - 7.2
  - 7.3

before_script: composer install -n

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs
  - vendor/bin/phpstan analyze src tests
  - vendor/bin/infection --min-msi=90

after_script: vendor/bin/php-coveralls
